app/controllers/application_controller.rb
add basic_auth
for basic authentication
=> add_application.rb

app/controllers/application_controller.rb
本番環境のみで動作するようbefore_action を定義
本番環境でのみBasic認証を動作させるため
=> commit_production?

config/deploy/production.rb
=> [WIP]add_basic

Gemfile, Gemfile.lock, config/database.yml, db/schema.rb
sqlite3 → mysql2
for DB accident
=> chenge_mysql2

README.md
#what 
READ MEの修正
#why
DB設計の概要を知るために必要
=> ok no hazu

app/assets/stylesheets/_index.scss, app/assets/stylesheets/application.scss, app/assets/stylesheets/mixin/_mixin.scss, app/assets/stylesheets/modules/_banner.scss, app/assets/stylesheets/modules/_header.scss, app/assets/stylesheets/modules/_main.scss, app/assets/stylesheets/modules/_variable.scss, app/views/products/index.html.haml, app/views/shared/_banner.html.haml, app/views/shared/_footer.html.haml, app/views/shared/_header.html.haml, app/views/shared/_main.html.haml
WHAT
メインとなるビューのhamlとscssを作成。
WHY
アプリケーションのindexを作成して本番環境でも見れるようにするため。
=> Products index review

config/routes.rb
=> exchange_routes_index

app/assets/stylesheets/application.scss, db/migrate/20200219090006_remove_prefecture_from_products.rb, db/migrate/20200219094001_remove_prefecture_id_from_products.rb, db/schema.rb
#why
master-fileで、pending migration　errorが発生したため、修正が必要。
#what
pending migrateとなっていたため、
migration　ファイルの修正を行なった。
=> EDIT DB comp

app/assets/stylesheets/modules/_footer.scss, app/assets/stylesheets/modules/_header.scss, app/assets/stylesheets/modules/_mypage.scss, app/views/users/show.html.haml
#What
マイページの実装
#Why
マイページ情報の搭載
=> Create mypage view

app/assets/stylesheets/modules/_header.scss, app/controllers/products_controller.rb, app/views/shared/_header.html.haml, app/views/shared/_header_child.html.haml, app/views/shared/_header_grandchild.html.haml, app/views/shared/_header_parent.html.haml
WHY
カテゴリのプルダウンメニューを搭載。コントローラーにカテゴリを取得するインスタンス変数を記載。
WHAT
カテゴリ一覧を見れるようにするため。
=> Product index view update2

app/assets/stylesheets/modules/_header.scss
#What
ヘッダーのビュー修正
#Why
本番環境での動作確認のため
=> revised header view

app/controllers/products_controller.rb, app/controllers/users_controller.rb
#What
@parentsの変数をユーザーコントローラへ入力
#why
マイページに@parentsを表示するため
=> Add @parents into users controller

app/views/devise/registrations/new_address.html.haml, db/migrate/20200214082129_create_products.rb, db/migrate/20200218115837_create_addresses.rb, db/migrate/20200218144128_add_phone_number_to_address.rb, db/migrate/20200218144748_remove_prefecture_from_address.rb, db/migrate/20200219032021_create_brands.rb, db/migrate/20200219100349_change_data_prifecture_to_products.rb, db/schema.rb
migrate-fileの修正
id等の修正を行い、登録できるようにした。
=> Edit migrationfile and new user

db/migrate/20200225040813_products.rb, db/schema.rb
ブランドIDに外部キー制約を追加した。
ブランドIDとproductsテーブルを紐づけるために必要
=> first commit

app/assets/stylesheets/devise/_login.scss, app/assets/stylesheets/devise/_new.scss, app/controllers/users/registrations_controller.rb, app/models/address.rb, app/views/devise/registrations/new_address.html.haml
validationが偏っていたため、修正を行った。
#why
必要な情報を登録時にばりデートするために必要。
=> validation comp

Gemfile.lock, app/controllers/products_controller.rb, app/views/products/edit.html.haml, app/views/shared/_showProduct.html.haml, config/routes.rb, db/schema.rb
=> edit first commit

app/assets/javascripts/cards.coffee, app/assets/javascripts/category.js, app/controllers/products_controller.rb, app/views/products/edit.html.haml, app/views/shared/_product_new.html.haml
再編集時に無限に出てくるため、修正が必要
#what
removeを追加した。
=> カテゴリ再選択時のdivタグ要素を消した。

app/assets/javascripts/category.js, app/assets/stylesheets/_products_new.scss, app/views/shared/_product_new.html.haml
=> 商品出品ページの見た目を修正

app/controllers/products_controller.rb, app/views/products/index.html.haml, app/views/shared/_account_header.html.haml, app/views/shared/_camera.html.haml, app/views/shared/_showProduct.html.haml
削除機能とビューを一部修正。
ユーザーが記事を削除できるようにするため。
=> Product delete create

app/controllers/products_controller.rb, app/views/products/edit.html.haml, app/views/shared/_product_new.html.haml
編集ページに遷移した際にプルダウンの情報を保持させる
編集する際にすでに登録されている情報は重要なため
=> fixed_pulldown

app/uploaders/image_uploader.rb, config/deploy.rb, config/initializers/carrierwave.rb
S3での画像アップロードに必要な設定の追加
本番環境での画像アップロードはS3を利用するため
＞五十嵐さんへ
　carrierwave.rbの３箇所？くらい記載をお願いします。
=> add_s3_upload_conf

app/assets/javascripts/category.js, app/controllers/products_controller.rb, app/models/product.rb, app/views/products/_product.html.haml, app/views/products/edit.html.haml, app/views/shared/_product_new.html.haml, spec/factories/brand.rb, spec/factories/categorys.rb, spec/factories/products.rb, spec/models/product_spec.rb, spec/rails_helper.rb
　コントローラのupdateメソッドの編集を行った。
　updateでデータを保存できるために必要
=> Create update-method_products controller

app/assets/javascripts/category.js, app/assets/stylesheets/modules/_main.scss, app/assets/stylesheets/modules/_show.scss, app/controllers/products_controller.rb, app/models/image.rb, app/models/product.rb, app/views/products/_brand.html.haml, app/views/products/_product.html.haml, app/views/products/edit.html.haml, app/views/shared/_showProduct.html.haml, config/routes.rb
カテゴリー機能の編集機能を実装。indexの仕様も一部変更。画像が投稿されなくても、表示されるように。
編集機能でカテゴリが変えられるようにするため。
=> Category create

app/controllers/purchase_controller.rb
#What 
商品購入機能を再度修正
#Why
商品購入機能を実装するため
=> changed purchase controller

app/assets/stylesheets/modules/_show.scss, app/views/login/_header.html.haml, app/views/purchase/_header.html.haml, app/views/shared/_account_header.html.haml, app/views/shared/_showProduct.html.haml
細部のロゴの変更（メルカリ→FURIMA）
購入ボタンの色味変更
レイアウト調整
=> Change logo

app/views/cards/index.html.haml, app/views/cards/show.html.haml, app/views/login/_footer.html.haml, app/views/purchase/_footer.html.haml, app/views/shared/_account_footer.html.haml, app/views/users/show.html.haml
メルカリと記載されている箇所の変更
リンク先がメルカリになっているアイコンのリンク先を変更
正しいページ遷移実装のため
=> cange_link_etc

app/assets/stylesheets/devise/_login.scss, app/assets/stylesheets/devise/_new.scss, app/assets/stylesheets/devise/_newaddress.scss, app/assets/stylesheets/modules/_account_header.scss, app/views/login/_footer.html.haml, app/views/login/_header.html.haml, app/views/purchase/_footer.html.haml, app/views/shared/_showProduct.html.haml
=> change_btn-color

app/assets/javascripts/products_newAddImage.js, app/views/shared/_product_new.html.haml, config/locales/devise.ja.yml, config/locales/ja.yml
エラー文を日本語化
#Why
エラー文章をわかりやすくするため
=> exchange_error

app/controllers/products_controller.rb, app/views/products/edit.html.haml
商品詳細編集の実装
出品者が商品の情報を編集できるように。
作業分担の為、マージを先してしまいました。
コネクタにて相談済み。
=> Mastercopy edit update

app/assets/stylesheets/application.scss, app/assets/stylesheets/product/_new.scss, app/assets/stylesheets/purchase/_purchase.scss, app/views/products/new.html.haml, app/views/purchase/_purchase.html.haml
・商品購入ページの発送先住所のリンク先を修正（支払い先ページ→住所入力ビュー）
・購入ページにて商品情報がはみ出す問題の修正
・商品出品ページのCSSリファクタリング
・確認により発見した問題の修正のため
・コードをシンプルにして、わかりやすくするため
=> OrganizingFilesRefactoring_Igarashi

app/controllers/products_controller.rb
productのコントローラーを一部before-actionにまとめた。
可読性を上げるため。
=> controller-edit

app/assets/stylesheets/devise/_new.scss, app/assets/stylesheets/modules/_camera.scss, app/assets/stylesheets/modules/_variable.scss, app/assets/stylesheets/product/_new.scss, app/assets/stylesheets/product/_show.scss, app/assets/stylesheets/purchase/_purchase.scss, app/assets/stylesheets/user/_mypage.scss, app/assets/stylesheets/useraddress/_form_input_address.scss
一部の色を赤から青に変更。変数が使用されていないところを変数に変更。
コードに統一感を持たせるため。
=> Color edit

README.md
#What
README修正
#Why
最新版のデータベースファイルを参照できるようにするため
=> Revised_readme
